export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESSFUL = "ADD_PRODUCT_SUCCESSFUL";
export const ADD_PRODUCT_ERROR= "ADD_PRODUCT_ERROR";

export const LOADING_DOWNLOAD_PRODUCTS = "LOADING_DOWNLOAD_PRODUCTS";
export const DOWNLOAD_PRODUCTS_SUCCESSFUL = "DOWNLOAD_PRODUCTS_SUCCESSFUL";
export const DOWNLOAD_PRODUCTS_ERROR = "DOWNLOAD_PRODUCTS_ERROR";

export const GET_PRODUCT_DELETE = "GET_PRODUCT_DELETE"; 
export const PRODUCT_DELETED_SUCCESSFUL = "PRODUCT_DELETED_SUCCESSFUL";
export const PRODUCT_DELETED_ERROR = "PRODUCT_DELETED_ERROR";

export const GET_PRODUCT_EDIT = "GET_PRODUCT_EDIT"; 
export const NEW_PRODUCT_EDIT = "NEW_PRODUCT_EDIT";
export const PRODUCT_EDIT_SUCCESSFUL = "PRODUCT_EDIT_SUCCESSFUL";
export const PRODUCT_EDIT_ERROR = "PRODUCT_EDIT_ERROR";



